training:
  training_steps: 300
  num_workers: 6
env_config:
  centralized: False
  continuous: False
  joint_learning_progress: 0
  learning_progress: 0
  double_condition: False
  alignment_percentage: 0.25