training:
  training_steps: 300
  num_workers: 10
env_config:
  centralized: False
  population_size: 2
  # True -> consider all goals
  # False -> consider only cooperative goals
  all_goals: True
  alignment_percentage: 0.21739
  new_reward: True
  reward_multiplier: 4
