training:
  training_steps: 300
  num_workers: 6
env_config:
  centralized: False
  eps_communication: 0.15
  # True -> consider all goals
  # False -> consider only cooperative goals
  all_goals: True
  population_size: 4
communication: "basic"
