training:
  training_steps: 1000
  num_workers: 10
env_config:
  centralized: False
  population_size: 2
  # True -> consider all goals
  # False -> consider only cooperative goals
  all_goals: True
  new_reward: True
  reward_multiplier: 2
communication: "centralized_critic"
