training:
  training_steps: 1000
  num_workers: 10
env_config:
  centralized: False
  population_size: 2
  # True -> consider all goals
  # False -> consider only cooperative goals
  all_goals: False
  new_reward: True
checkpoint: /gpfsscratch/rech/imi/uzw47io/elias_expe/2_agents/cooperative/modified_reward/6_landmarks/independent/2022-10-05_16-27-488vn8uoj5/checkpoint_001000/checkpoint-1000
