training:
  training_steps: 500
  num_workers: 6
env_config:
  centralized: False
  continuous: False
  all_goals: True
  new_reward: False
communication: "basic_naming"
# train_matrix: True
# checkpoint: "/home/elias/workspace/imgc-marl/scripts/testing420/2022-08-09_15-00-54jkrbth14/checkpoint_000001/checkpoint-1"
