training:
  training_steps: 1000
  num_workers: 6
env_config:
  centralized: False
  eps_communication: 0.15
  population_size: 8
  # True -> consider all goals
  # False -> consider only cooperative goals
  all_goals: True
communication: "basic"
