from imgc_marl.policies.basic_communication import BasicCommunicationTrainer
from imgc_marl.policies.full_communication import FullCommunicationTrainer
from imgc_marl.policies.basic_naming_game import BasicNamingTrainer
