training:
  training_steps: 300
  num_workers: 6
env_config:
  centralized: False
  population_size: 4
  # Allowed goals during training
  allowed_goals: [[0,0,1], [0,1,0], [1,0,0]]
  new_reward: False
