from imgc_marl.models.basic_communication import BasicCommunicationNetwork
from imgc_marl.models.full_communication import FullCommunicationNetwork
from imgc_marl.models.basic_naming_game import BasicNamingNetwork
from imgc_marl.models.centralized_critic_models import TorchCentralizedCriticModel